---
dist: xenial
language: python
os: linux
python: "3.9"
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - DOCKER_BASE_IMAGE=debian:bookworm-slim
    - DOCKER_BASE_IMAGE=debian:buster-slim 
    - DOCKER_BASE_IMAGE=debian:stretch-slim

script:
  - export DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE}
  - export PG_MAJOR_RELEASE=${PG_MAJOR_RELEASE}
  - pipenv run molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = master
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
